#!/usr/bin/env python3
"""Rebuild the puzzle tiles in index.html from the puzzle pages.

Each puzzle page (puzzles/<slug>/index.html) is the single source of truth
for its tile on the index:

  title   <h1> (fallbacks: <meta name="puzzle:title">, then <title>)
  desc    <p class="rule"> (fallback: <meta name="puzzle:rule">)

JS-rendered pages (emptying-poles) keep title/rule in those metas and render
them from there, so the metas stay the single source. Meta content may hold
entity-escaped markup (&lt;em&gt;...) — it is unescaped here.
  tags    <meta name="puzzle:tags" content="a · b">
  emblem  <template class="tile-emblem"> holding the tile SVG

Tile order comes from puzzles/order.txt (one slug per line, '#' comments).
The generated tiles replace whatever sits between the build markers in
index.html. Run from anywhere; paths are repo-relative to this file.

A git pre-commit hook runs this automatically; run by hand after editing
a puzzle's title/rule/tags/emblem to see the index update locally.
"""
import html
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "index.html"
ORDER = ROOT / "puzzles" / "order.txt"
MARK_OPEN = "<!-- tiles:generated by scripts/build_index.py; edit the puzzle pages, not this block -->"
MARK_CLOSE = "<!-- /tiles:generated -->"


def fail(msg):
    sys.exit(f"build_index: {msg}")


def extract(pattern, text, flags=re.S):
    m = re.search(pattern, text, flags)
    return m.group(1).strip() if m else None


def tile_title(page, slug):
    h1 = extract(r"<h1[^>]*>(.*?)</h1>", page)
    if h1 is None:
        meta = extract(r'<meta name="puzzle:title" content="([^"]*)"', page)
        h1 = html.unescape(meta) if meta is not None else None
    if h1 is None:
        h1 = extract(r"<title>(.*?)</title>", page)
    if h1 is None:
        fail(f"{slug}: no <h1>, no <meta name=\"puzzle:title\">, no <title>")
    h1 = re.sub(r"<br\s*/?>", " ", h1)
    h1 = re.sub(r"<[^>]+>", "", h1)  # keep text and entities only
    return re.sub(r"\s+", " ", h1).strip()


def tile_rule(page, slug):
    rule = extract(r'<p class="rule"[^>]*>(.*?)</p>', page)
    if rule is None:
        meta = extract(r'<meta name="puzzle:rule" content="([^"]*)"', page)
        rule = html.unescape(meta) if meta is not None else None
    if rule is None:
        fail(f"{slug}: no <p class=\"rule\"> and no <meta name=\"puzzle:rule\">")
    return re.sub(r"\s+", " ", rule).strip()


def tile_tags(page, slug):
    tags = extract(r'<meta name="puzzle:tags" content="([^"]*)"', page)
    if tags is None:
        fail(f"{slug}: missing <meta name=\"puzzle:tags\" content=\"a · b\">")
    parts = [p.strip() for p in tags.split("·") if p.strip()]
    if not parts:
        fail(f"{slug}: empty puzzle:tags")
    return "<br>".join(parts)


def tile_emblem(page, slug):
    svg = extract(r'<template class="tile-emblem">(.*?)</template>', page)
    if svg is None:
        fail(f"{slug}: missing <template class=\"tile-emblem\"> with the tile SVG")
    return "\n".join("            " + ln.strip() for ln in svg.splitlines() if ln.strip())


def build_tile(slug, num):
    path = ROOT / "puzzles" / slug / "index.html"
    if not path.exists():
        fail(f"{slug}: {path} not found (fix puzzles/order.txt?)")
    page = path.read_text(encoding="utf-8")
    return f"""      <li data-puzzle="{slug}">
        <a href="puzzles/{slug}/index.html">
          <span class="num">{num:02d}</span>
          <span class="thumb" aria-hidden="true">
{tile_emblem(page, slug)}
          </span>
          <span class="body">
            <span class="title">{tile_title(page, slug)}</span>
            <span class="desc">{tile_rule(page, slug)}</span>
          </span>
          <span class="tag">{tile_tags(page, slug)}</span>
        </a>
      </li>"""


def main():
    slugs = [ln.strip() for ln in ORDER.read_text(encoding="utf-8").splitlines()
             if ln.strip() and not ln.strip().startswith("#")]
    if not slugs:
        fail(f"{ORDER} lists no puzzles")

    tiles = "\n".join(build_tile(s, i) for i, s in enumerate(slugs, 1))
    index = INDEX.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(MARK_OPEN) + r".*?" + re.escape(MARK_CLOSE), re.S)
    if not pattern.search(index):
        fail(f"index.html is missing the tile markers ({MARK_OPEN})")
    rebuilt = pattern.sub(MARK_OPEN + "\n" + tiles + "\n      " + MARK_CLOSE, index)

    if rebuilt != index:
        INDEX.write_text(rebuilt, encoding="utf-8")
        print(f"build_index: rebuilt {len(slugs)} tiles -> index.html")
    else:
        print(f"build_index: index.html already up to date ({len(slugs)} tiles)")


if __name__ == "__main__":
    main()
